"""Add name of the API Key in user_api_keys table

Revision ID: e5f21fc1d3f1
Revises: ca807c4e90c3
Create Date: 2024-12-20 01:20:43.251890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f21fc1d3f1'
down_revision: Union[str, None] = 'ca807c4e90c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_api_keys', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_api_keys', 'name')
    # ### end Alembic commands ###
